const $ = (id) => document.getElementById(id);
const csv = (text) => {
  const rows=[]; let row=[], cell='', quote=false;
  for(let i=0;i<text.length;i++){const c=text[i], n=text[i+1]; if(c==='"'){if(quote&&n==='"'){cell+='"';i++}else quote=!quote} else if(c===','&&!quote){row.push(cell);cell=''} else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>x!==''))rows.push(row);row=[];cell=''} else cell+=c} if(cell||row.length){row.push(cell);rows.push(row)}
  const headers=rows.shift(); return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));
};
const typeOf = n => n.includes('Indian Institute of Technology') ? 'IIT' : n.includes('National Institute of Technology') ? 'NIT' : (n.includes('IIIT') || n.includes('Indian Institute of Information Technology')) ? 'IIIT' : 'GFTI';
const short = n => n.replace('National Institute of Technology','NIT').replace('Indian Institute of Technology','IIT').replace('Indian Institute of Information Technology','IIIT').replace(/, /g,' ');
const norm = s => s.toLowerCase().replace(/[^a-z0-9]/g,'');
const tiers = {"Microsoft":"Tier 1 Product","Google":"Tier 1 Product","Amazon":"Tier 1 Product","Adobe":"Tier 1 Product","Qualcomm":"Core Hardware","Samsung":"Core Hardware","Siemens":"Core Hardware","Bosch":"Core Hardware","Oracle":"Tier 2 Product","IBM":"Tier 2 Product","Deloitte":"Consulting","Accenture":"Consulting","TCS":"Service/IT","Infosys":"Service/IT","Wipro":"Service/IT","Capgemini":"Service/IT","Cognizant":"Service/IT","HCLTech":"Service/IT","Tech Mahindra":"Service/IT","L&T":"Core Hardware"};
const state={josaa:[],mous:[],city:'Bengaluru',skills:{'Data Structures':6,'System Design':4,'Core Engineering':5,'SQL / Databases':6,'OOP':7}};
const skillBench={'Data Structures':8,'System Design':7,'Core Engineering':6,'SQL / Databases':7,'OOP':7};

function options(el, values){el.innerHTML=values.map(v=>`<option value="${v.replace(/"/g,'&quot;')}">${short(v)}</option>`).join('')}
function selectedRows(){const college=$('college').value, program=$('branch').value, category=$('category').value, gender=$('gender').value, home=$('homeState').checked;let r=state.josaa.filter(x=>x.Institute===college&&x['Academic Program Name']===program); const preferredQuota=home?'HS':'OS'; const exact=r.filter(x=>x['Seat Type']===category&&x.Gender===gender&&x.Quota===preferredQuota); if(exact.length)return [exact,`Exact ${home?'Home State':'Other State'} / ${category} quota`]; const close=r.filter(x=>x['Seat Type']===category&&x.Gender===gender); if(close.length)return [close,`No exact quota record; showing closest ${category} / ${gender} 2024 record`]; const wider=r.filter(x=>x['Seat Type']===category); if(wider.length)return [wider,`No gender/quota match; showing ${category} 2024 benchmark`]; return [r,`No requested category record; showing available 2024 programme benchmark`];}
function estimate(rank,type){if(type==='IIT'){const marks=Math.max(45,Math.min(330,Math.round(330-50*Math.log10(Math.max(rank,1)))));return {primary:marks, suffix:' / 360', range:`Safety band: ${Math.max(0,marks-10)}–${Math.min(360,marks+10)} marks`, percent:marks/3.6,label:'JEE Advanced aggregate marks'}} const percentile=Math.max(75,Math.min(99.95,100-2.6*Math.log10(Math.max(rank,1)))); const marks=Math.round(Math.max(45,Math.min(290,300*(percentile-70)/30)));return {primary:percentile.toFixed(2),suffix:' percentile',range:`About ${Math.max(0,marks-12)}–${Math.min(300,marks+12)} / 300 raw-score band`,percent:percentile,label:'JEE Main expected percentile'};}
function updateTarget(){const [rows,note]=selectedRows(); const type=$('instituteType').value; let opening,closing; if(rows.length){opening=Math.min(...rows.map(x=>+x['Opening Rank']).filter(Boolean));closing=Math.max(...rows.map(x=>+x['Closing Rank']).filter(Boolean));} else {opening=12000;closing=18000} const e=estimate(closing,type), difficulty=Math.round(Math.max(18,Math.min(97,100-15*Math.log10(Math.max(closing,1))))); $('selectedTitle').textContent=`${short($('college').value)} · ${$('branch').value.split('(')[0].trim()}`;$('openingRank').textContent=opening.toLocaleString('en-IN');$('closingRank').textContent=closing.toLocaleString('en-IN');$('selectionNote').textContent=note;$('cutoffSource').textContent=rows.length?'2024 Round 5 closing cutoff · supplied JoSAA data':'No matching cutoff row found; modeled planning benchmark.';$('examLabel').textContent=e.label;$('targetScore').textContent=e.primary;$('scoreSuffix').textContent=e.suffix;$('rangeText').textContent=e.range;$('scoreBar').style.width=`${e.percent}%`;$('difficulty').textContent=difficulty;$('gaugePath').style.strokeDashoffset=220-(220*difficulty/100);$('difficultyCopy').textContent=difficulty>80?'Elite target — demands sustained top-percentile execution.':difficulty>55?'Highly competitive — build a sizeable safety margin.':'Achievable target — consistency can move the outcome.'; updateMou();updateROI();}
function syntheticMou(college){const templates=[['Tata Research & Design','Tier 1 Product',18.5],['NexGen Systems','Core Hardware',12.4],['CloudScale Labs','Tier 2 Product',15.8]];return templates.map(([Company,Tier,pkg],i)=>({College:short(college),Company,MOU_Status:'Synthetic','Placement_Rate_%':50-i*7,Avg_Package_LPA:pkg,Highest_Package_LPA:pkg*2.2,Eligible_Branches:'All',Internship_Program:'Yes',tier:Tier}));}
function updateMou(){let col=$('college').value, key=norm(short(col));let rows=state.mous.filter(x=>{const a=norm(x.College),b=key;return a.includes(b)||b.includes(a)||a.replace('nit','').includes(b.replace('nit',''))});const isSynthetic=!rows.length;if(isSynthetic)rows=syntheticMou(col);rows.forEach(x=>x.tier=tiers[x.Company]||x.tier||'Tier 2 Product'); $('mouBadge').textContent=isSynthetic?'Synthetic coverage':'Supplied MoU data';$('companyCards').innerHTML=rows.map(x=>`<div class="company-card"><div><b>${x.Company}</b><small>${x.tier} · ${x.Eligible_Branches}</small></div><strong>${x.Avg_Package_LPA} LPA</strong></div>`).join(''); const counts={};rows.forEach(x=>counts[x.tier]=(counts[x.tier]||0)+1);const colors=['#AEB99F','#AAB8BC','#C69B83','#C9B77D','#B8A9C9'];let start=0,segments=[];Object.entries(counts).forEach(([name,count],i)=>{let end=start+count/rows.length*360;segments.push(`${colors[i]} ${start}deg ${end}deg`);start=end});$('donut').style.background=`conic-gradient(${segments.join(',')})`;$('donutText').textContent=`${rows.length}\nrecruiters`;$('legend').innerHTML=Object.entries(counts).map(([n,c],i)=>`<span><i style="background:${colors[i]}"></i>${n} · ${Math.round(c/rows.length*100)}%</span>`).join('');const prime=rows.reduce((a,b)=>+a.Avg_Package_LPA>+b.Avg_Package_LPA?a:b);$('mouInsight').textContent=`${isSynthetic?'Modeled opportunity:':'MoU insight:'} ${prime.Company} offers ${prime.Internship_Program==='Yes'?'an internship pathway':'placement engagement'} for ${prime.Eligible_Branches} (${prime.Avg_Package_LPA} LPA average).`;state.currentMou=rows;}
function renderSkills(){const list=$('skillSliders');list.innerHTML=Object.entries(state.skills).map(([name,value])=>`<div class="skill"><div><span>${name}</span><b id="skill-${name}">${value}/10</b></div><input type="range" min="1" max="10" value="${value}" data-skill="${name}"></div>`).join('');list.querySelectorAll('input').forEach(el=>el.addEventListener('input',()=>{state.skills[el.dataset.skill]=+el.value;renderSkills();renderRadar()}));renderRadar();}
function renderRadar(){const names=Object.keys(state.skills), cx=125,cy=110,r=76,point=(v,i)=>{let a=-Math.PI/2+i*2*Math.PI/names.length;return `${cx+Math.cos(a)*r*v/10},${cy+Math.sin(a)*r*v/10}`};const poly=o=>names.map((n,i)=>point(o[n],i)).join(' ');let grid=[.33,.66,1].map(q=>`<polygon points="${names.map((n,i)=>point(q*10,i)).join(' ')}" fill="none" stroke="#3a4d48"/>`).join('');let axes=names.map((n,i)=>{let p=point(10,i),label=point(12.2,i);return `<line x1="${cx}" y1="${cy}" x2="${p}" y2="${p}" stroke="#3a4d48"/><text x="${label.split(',')[0]}" y="${label.split(',')[1]}" fill="#90a49b" font-size="8" text-anchor="middle">${n.split(' ')[0]}</text>`}).join('');$('radar').innerHTML=`${grid}${axes}<polygon points="${poly(skillBench)}" fill="rgba(255,175,113,.1)" stroke="#ffaf71" stroke-width="2"/><polygon points="${poly(state.skills)}" fill="rgba(119,230,182,.22)" stroke="#77e6b6" stroke-width="2"/>`; const match=Math.round(names.reduce((s,n)=>s+Math.min(state.skills[n]/skillBench[n],1),0)/names.length*100);$('matchScore').textContent=`${match}%`;const gaps=names.map(n=>[n,skillBench[n]-state.skills[n]]).sort((a,b)=>b[1]-a[1]).slice(0,3);$('priorityTopics').innerHTML=gaps.map(([n,g])=>`<span class="topic">${g>0?'Prioritise ':'Strengthen '}${n}</span>`).join('');}
function updateROI(){const tuition=+$('tuition').value,loan=+$('loan').value,rate=+$('interest').value/1200,months=120;const emi=loan?loan*100000*rate*Math.pow(1+rate,months)/(Math.pow(1+rate,months)-1):0;const pkg=(state.currentMou||[]).reduce((s,x)=>s+(+x.Avg_Package_LPA||0),0)/((state.currentMou||[]).length||1);const cityCost={Bengaluru:55000,Hyderabad:44000,'Tier-2':30000}[state.city];const take=Math.max(25000,pkg*100000/12*.79-cityCost);const payback=Math.ceil(tuition*100000/Math.max(1,take-emi));$('tuitionOut').textContent=`₹${tuition}L`;$('loanOut').textContent=`₹${loan}L`;$('rateOut').textContent=`${$('interest').value}%`;$('emi').textContent=`₹${Math.round(emi).toLocaleString('en-IN')}`;$('takeHome').textContent=`₹${Math.round(take).toLocaleString('en-IN')}`;$('payback').textContent=`${payback} months`;}
function upgrade(){const cgpa=+$('cgpa').value,intern=+$('internships').value,badges=+$('badges').value;const p=Math.min(92,Math.round(6+(cgpa-6)*11+intern*10+badges*5));$('cgpaOut').textContent=cgpa.toFixed(1);$('internOut').textContent=intern;$('badgeOut').textContent=badges;$('tierOneProb').textContent=`${p}%`;$('probBar').style.width=`${p}%`;const tasks=['Build fundamentals','Ship 2 projects','First internship','DSA consistency','Open-source / hackathon','Mock interviews','Placement sprint','Offer season'];$('timeline').innerHTML=tasks.map((t,i)=>`<div class="semester ${i<Math.min(8,Math.floor((cgpa-6)*1.4+intern*1.5+badges*.45))?'done':''}" data-i="${i}"><b>S${i+1}</b>${t}</div>`).join('');document.querySelectorAll('.semester').forEach(s=>s.addEventListener('click',()=>s.classList.toggle('done')))}
function findByRank(){const raw=$('rankValue').value, rank=+raw;const resultsEl=$('rankResults'), noteEl=$('rankNote'), countEl=$('rankCount');if(!raw||!rank||rank<1){resultsEl.innerHTML='';noteEl.textContent='Enter your rank above to see every 2024 Round 5 seat that closed at or beyond it.';countEl.textContent='Enter a rank';return;}const type=$('rankInstituteType').value, cat=$('rankCategory').value, gender=$('rankGender').value, home=$('rankHomeState').checked, quota=home?'HS':'OS';let base=state.josaa.filter(x=>(type==='ANY'||typeOf(x.Institute)===type)&&x['Seat Type']===cat&&x.Gender===gender);let quotaRows=base.filter(x=>x.Quota===quota);let pool=quotaRows.length?quotaRows:base;let usedFallback=!quotaRows.length&&base.length>0;let eligible=pool.filter(x=>{const closing=+x['Closing Rank'];return closing&&rank<=closing}).sort((a,b)=>+a['Closing Rank']-+b['Closing Rank']);countEl.textContent=`${eligible.length} seat${eligible.length===1?'':'s'} in reach`;if(!eligible.length){resultsEl.innerHTML='';noteEl.textContent=`No 2024 Round 5 seat closed at or beyond rank ${rank.toLocaleString('en-IN')} for these filters. Try a broader institute type or category.`;return}noteEl.textContent=usedFallback?`Showing all quotas — no ${home?'Home State':'Other State'} record matched these filters.`:`Ranked by closing rank · ${home?'Home State':'Other State'} quota · ${cat} / ${gender==='Gender-Neutral'?'Gender-neutral':'Female-only'}`;resultsEl.innerHTML=eligible.map(x=>`<div class="rank-result"><div><b>${short(x.Institute)}</b><small>${x['Academic Program Name']}</small></div><div class="rank-result-meta"><span class="type-pill">${typeOf(x.Institute)}</span><span class="closing">Closing ${(+x['Closing Rank']).toLocaleString('en-IN')}</span></div></div>`).join('');}
function bind(){['instituteType','college','branch','category','gender','homeState'].forEach(id=>$(id).addEventListener('change',()=>{if(id==='instituteType')fillColleges();else if(id==='college')fillBranches();updateTarget()}));['tuition','loan','interest'].forEach(id=>$(id).addEventListener('input',updateROI));document.querySelectorAll('.city').forEach(b=>b.addEventListener('click',()=>{state.city=b.dataset.city;document.querySelectorAll('.city').forEach(x=>x.classList.toggle('active',x===b));updateROI()}));['cgpa','internships','badges'].forEach(id=>$(id).addEventListener('input',upgrade));['rankValue','rankInstituteType','rankCategory','rankGender','rankHomeState'].forEach(id=>$(id).addEventListener('input',findByRank));}
function fillColleges(){const type=$('instituteType').value;options($('college'),[...new Set(state.josaa.filter(x=>typeOf(x.Institute)===type).map(x=>x.Institute))].sort());fillBranches()}
function fillBranches(){const c=$('college').value;options($('branch'),[...new Set(state.josaa.filter(x=>x.Institute===c).map(x=>x['Academic Program Name']))].sort())}
async function init(){try{const [j,m]=await Promise.all([fetch('data/josaa_2024_round5.csv').then(x=>x.text()),fetch('data/college_company_mou.csv').then(x=>x.text())]);state.josaa=csv(j).filter(x=>x.Year==='2024');state.mous=csv(m);fillColleges();bind();renderSkills();updateTarget();upgrade();findByRank()}catch(e){document.body.innerHTML='<main><h1>Unable to load data</h1><p>Run this folder through a local web server (see README.md).</p></main>';console.error(e)}}init();
